apiVersion: v1
kind: Pod
metadata:
  name: service-lb
  labels:
    course: DevOps-lb
    Trainer: "SivakumarReddy"
spec:
  # list of containers
  containers:
  - name: service-demo-lb
    image: nginx
    ports:
    - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service-lb
spec:
  # list of containers
  type: LoadBalancer
  selector:
    course: DevOps-lb
    Trainer: "SivakumarReddy"
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
