apiVersion: v1
kind: Pod
metadata:
  name: resource-demo
  labels:
    purpose: resouces-demo
spec:
  containers:
  - name: resource
    image: nginx
    ports:
    - containerport: 80
    resources:
      requests:
        cpu: "100m"
        memory: "68Mi"
      limits:
        cpu: "200m"
        memory: "128Mi"